import android.content.ActivityNotFoundException;
import android.content.Intent;
import android.os.Bundle;
import android.speech.RecognizerIntent;
import android.support.v7.app.AppCompatActivity;
import android.view.View;
import android.widget.ImageButton;
import android.widget.TextView;

import java.util.ArrayList;
import java.util.Locale;
import java.util.Random;

import thuet.bastien.myapplication.R;
import thuet.bastien.myapplication.wait;thuet.bastien.myapplication;

import android.content.ActivityNotFoundException;
import android.content.Intent;
import android.os.Bundle;
import android.speech.RecognizerIntent;
import android.support.v7.app.AppCompatActivity;
import android.view.View;
import android.widget.ImageButton;
import android.widget.TextView;
import java.util.ArrayList;
import java.util.Locale;
import java.util.Random;


public class MainActivity extends AppCompatActivity {

    String list_expr[] = {"avoir du plomb dans l’aile ", "avoir un fil à la patte ",
            "avoir un sacré coup de patte ",
            "donner des ailes ",
            "faire patte de velours ",
            "graisser la patte ",
            "montrer patte blanche ",
            "ne pas casser trois pattes à un canard ",
            "prendre sous son aile ",
            "voler de ses propres ailes ",
            "avoir le bras long ",
            "coûter un bras (et une jambe) ",
            "en garder sous le coude ",
            "être dans les bras de Morphée ",
            "les bras m’en tombent ",
            "lever le coude ",
            "ne pas se moucher du coude ",
            "rester les bras croisés ",
            "se retrousser les manches ",
            "se serrer les coudes ",
            "tomber dans les bras de Morphée ",
            "à cœur perdu ",
            "à cœur vaillant rien d’impossible ",
            "avoir bon cœur ",
            "avoir le cœur au bord des lèvres ",
            "avoir le cœur brisé ",
            "avoir le cœur sec ",
            "avoir le cœur gros ",
            "avoir le cœur sur la main ",
            "avoir mal au cœur ",
            "avoir un cœur d’artichaut ",
            "avoir un cœur de pierre ",
            "avoir un pincement au cœur ",
            "coup de cœur ",
            "dire ce qu’on a sur le cœur ",
            "faire contre mauvaise fortune bon cœur ",
            "faire la bouche en cœur ",
            "faire le joli cœur ",
            "mains froides, cœur chaud ",
            "ouvrir son cœur ",
            "prendre à cœur ",
            "avoir des doigts de fée ",
            "avoir du doigté ",
            "avoir les pouces verts ",
            "donner un coup de pouce ",
            "manger sur le pouce ",
            "mettre à l’index ",
            "mettre le doigt dans l’engrenage ",
            "mettre le doigt sur ",
            "mon petit doigt m’a dit ",
            "montrer du doigt ",
            "se mettre le doigt dans l’œil ",
            "se tourner les pouces ",
            "s’en mordre les doigts ",
            "toucher du doigt ",
            "avoir des fourmis dans les jambes ",
            "avoir des mollets de coq ",
            "avoir la cuisse légère ",
            "avoir les chevilles qui enflent ",
            "avoir les jambes en coton ",
            "écarter les cuisses ",
            "faire une belle jambe ",
            "faire une partie de jambes en l’air ",
            "mettre à genoux ",
            "prendre ses jambes à son cou ",
            "se croire sorti de la cuisse de Jupiter ",
            "traiter par dessous la jambe ",
            "armé jusqu’aux dents ",
            "avoir la dent dure ",
            "avoir la langue bien pendue ",
            "avoir le dernier mot ",
            "avoir les dents longues ",
            "avoir les dents qui rayent le parquet ",
            "avoir les dents qui rayent le plancher ",
            "avoir les dents mêlées ",
            "avoir un cheveu sur la langue ",
            "avoir une dent contre quelqu’un ",
            "bouche à oreille ",
            "claquer les dents ",
            "donner sa langue au chat ",
            "du bout des dents ",
            "en prendre plein les gencives ",
            "être mordu de quelque chose ",
            "être pendu aux lèvres de quelqu’un ",
            "être sur les dents ",
            "faire chanter quelqu’un ",
            "faire la bouche en cœur ",
            "faire la fine bouche ",
            "mordre la poussière ",
            "motus et bouche cousue ",
            "ne pas avoir sa langue dans sa poche ",
            "œil pour œil, dent pour dent ",
            "s’en tirer par la peau des dents (Canada) ",
            "tenir sa langue ",
            "avoir deux mains gauches ",
            "avoir la main baladeuse ",
            "avoir la main heureuse ",
            "avoir la main verte ",
            "avoir un poil dans la main ",
            "balayer d’un revers de main ",
            "donner un coup de main ",
            "dormir à poings fermés ",
            "en mettre sa main au feu ",
            "en mettre sa main à couper ",
            "en venir aux mains ",
            "manger dans la main ",
            "mettre la main à la pâte ",
            "ne pas y aller de main morte ",
            "prendre des gants ",
            "(se faire) prendre la main dans le sac ",
            "prendre son courage à deux mains ",
            "prêter main forte ",
            "s’en laver les mains ",
            "tendre la main ",
            "une main de fer dans un gant de velours ",
            "avoir le pied marin ",
            "avoir les deux pieds dans le même sabot ",
            "avoir les pieds sur terre ",
            "avoir pied ",
            "avoir un pied dans la tombe ",
            "botter en touche ",
            "casser les pieds ",
            "cirer les bottes de quelqu’un ",
            "couper l’herbe sous le pied ",
            "être bête comme ses pieds ",
            "être con comme un pied de chaise ",
            "faire des pieds et des mains ",
            "faire les cents pas ",
            "faire les pieds ",
            "marcher sur les plates bandes de quelqu’un ",
            "marcher sur les pieds de quelqu’un ",
            "mettre au pied du mur ",
            "mettre le pied à l’étrier ",
            "mettre les pieds dans le plat ",
            "mettre sur pied ",
            "ne pas arriver à la cheville ",
            "ne plus savoir sur quel pied danser ",
            "prendre son pied ",
            "se faire marcher dessus ",
            "se faire piétiner ",
            "se laisser marcher sur les pieds ",
            "ne pas se moucher du pied ",
            "ne pas se moucher du coude ",
            "se lever du mauvais pied ",
            "se lever du pied gauche ",
            "se tirer une balle dans le pied ",
            "trouver chaussure à son pied ",
            "avoir un cheveu sur la langue ",
            "avoir un poil dans la main ",
            "couper les cheveux en quatre ",
            "être de bon poil ",
            "parler dans sa moustache ",
            "parler dans sa barbe ",
            "reprendre du poil de la bête ",
            "être tiré par les cheveux ",
            "comme un cheveu sur la soupe ",
            "défiler à la queue leu-leu ",
            "faire la queue ",
            "faire une queue de poisson ",
            "finir en queue de poisson ",
            "la queue entre les jambes ",
            "sans queue ni tête ",
            "tirer le diable par la queue, ",
            "tirer le Diable par la queue ",
            "avoir du nez ",
            "avoir la tête comme un tambour ",
            "avoir la tête dans le cul ",
            "avoir la tête dans les nuages ",
            "avoir la tête sur les épaules ",
            "avoir une tête d’ange ",
            "avoir le couteau sous la gorge ",
            "avoir le nez fin ",
            "avoir le nez creux ",
            "avoir les oreilles qui sifflent ",
            "avoir quelqu’un dans le nez ",
            "avoir toute sa tête ",
            "avoir une idée derrière la tête ",
            "dormir sur ses deux oreilles ",
            "dominer de la tête et des épaules ",
            "en prendre plein la figure ",
            "en donner sa tête à couper ",
            "être le bec dans l’eau ",
            "être pris à la gorge ",
            "être tombé sur la tête ",
            "être une tête de lard ",
            "faire la tête ",
            "faire la tête au carré ",
            "garder la tête froide ",
            "mettre en joue ",
            "mettre le nez dehors ",
            "mettre sa tête à couper ",
            "n’avoir ni queue ni tête ",
            "ne pas avoir la tête à quelque chose ",
            "ne pas voir plus loin que le bout de son nez ",
            "ne rien avoir dans la tête ",
            "opiner du chef ",
            "opiner du bonnet ",
            "perdre la tête ",
            "piquer une tête ",
            "prendre la tête ",
            "rendre gorge ",
            "se creuser la tête ",
            "se prendre la tête ",
            "s’en prendre plein la gueule ",
            "sourire jusqu’aux oreilles ",
            "tendre l’oreille ",
            "tirer les vers du nez ",
            "tête de linotte ",
            "à l’œil ",
            "aller se faire voir ailleurs ",
            "avoir de la merde dans les yeux ",
            "avoir des yeux de lynx ",
            "avoir des yeux derrière la tête ",
            "avoir le compas dans l’œil ",
            "avoir les yeux plus gros que le ventre ",
            "avoir un œil au beurre noir ",
            "avoir un œil qui dit merde à l’autre ",
            "avoir une coquetterie dans l’œil ",
            "dévorer des yeux ",
            "faire de l’œil ",
            "faire des yeux de merlan frit ",
            "fermer les yeux ",
            "jeter de la poudre aux yeux ",
            "jeter un œil, jeter un coup d’œil ",
            "n’avoir rien à voir avec ",
            "ne pas avoir froid aux yeux ",
            "ne pas avoir les yeux en face des trous ",
            "ne toucher qu’avec les yeux ",
            "ouvrir l’œil ",
            "ouvrir les yeux ",
            "pleurer toutes les larmes de son corps ",
            "regarder d’un œil neuf ",
            "se fourrer le doigt dans l’œil ",
            "se fourrer le doigt dans l’œil jusqu’au coude ",
            "se rincer l’œil ",
            "sortir par les yeux ",
            "voir la Lune en plein jour ",
            "voir trente-six chandelles ",
            "y regarder à deux fois ",
            "voir des éléphants roses ",
            "voir des étoiles ",
            "avoir à l’œil ",
            "Gentil n'a qu'un œil ",
            "ne pas avoir les yeux dans sa poche ",
            "faire les yeux doux ",
            "regarder avec les yeux de l'amour ",
            "comme les yeux dans le bouillon ",
            "regarder d'un œil complaisant ",
            "regarder dans le blanc des yeux ",
            "en plein dans l’œil du cyclone ",
            "avoir un œil critique ",
            "avaler tout rond ",
            "avoir dans la peau ",
            "avoir de la veine ",
            "avoir des sueurs froides ",
            "avoir du monde au balcon ",
            "avoir le sang chaud ",
            "avoir l’estomac bien accroché ",
            "avoir l'estomac dans les talons ",
            "avoir l’estomac noué ",
            "bon sang ne saurait mentir ",
            "cracher ses poumons ",
            "cracher ses tripes ",
            "donner un os à ronger à quelqu’un ",
            "être à bout de nerfs ",
            "être pourri jusqu’à la moelle ",
            "être sur le cul ",
            "faire de vieux os ",
            "faire le dos rond ",
            "faire profil bas ",
            "glacer le sang ",
            "l’avoir dans l’os, l’avoir à l’os ",
            "n’avoir que la peau sur les os ",
            "passer ses nerfs sur quelqu’un ",
            "prendre des vessies pour des lanternes ",
            "rouler sa bosse ",
            "se faire un sang d’encre ",
            "se mettre la rate au court-bouillon ",
            "se serrer la ceinture ",
            "suer sang et eau ",
            "taper sur les nerfs ou taper sur le système ",
            "tomber sur un os ",
            "faire des pieds et des mains ",
            "sourd comme un pot ",
            "avoir des oursins dans les poches ",
            "engueuler comme du poisson pourri ",
            "être comme un poisson dans l’eau ",
            "être serrés comme des sardines ",
            "faire des yeux de merlan frit ",
            "faire une queue de poisson ",
            "finir en queue de poisson ",
            "glisser comme une anguille ",
            "méduser ",
            "noyer le poisson ",
            "panier de crabe ",
            "passer l’éponge ",
            "poisson d’avril ",
            "rire comme une baleine ",
            "bailler comme une huître ",
            "se fermer comme une huître ",
            "souffler comme un phoque ",
            "y avoir anguille sous roche ",
            "avoir des fourmis dans les jambes ",
            "avoir le bourdon ",
            "avoir le cafard ",
            "avoir une araignée dans le plafond ",
            "avoir une araignée au plafond ",
            "avoir une taille de guêpe ",
            "chercher des poux ",
            "chercher la petite bête ",
            "écrire en patte de mouche ",
            "être une grenouille de bénitier ",
            "être excité comme une puce ",
            "enculer les mouches ",
            "mouche du coche ",
            "être laid comme un pou ",
            "faire mouche ",
            "mettre la puce à l’oreille ",
            "on n’attrape pas des mouches avec du vinaigre ",
            "ne pas être piqué des hannetons ",
            "ne pas être piqué des vers ",
            "prendre la mouche ",
            "tirer les vers du nez ",
            "tuer le ver ",
            "acheter chat en poche ",
            "appeler un chat un chat ",
            "arriver comme un chien dans un jeu de quilles ",
            "avoir d’autres chats à fouetter ",
            "avoir des yeux de lynx ",
            "avoir du chien ",
            "avoir mangé du lion ",
            "avoir un chat dans la gorge ",
            "avoir un mal de chien ",
            "avoir une faim de loup ",
            "avoir une mémoire d’éléphant ",
            "caractère de cochon ",
            "changer de cheval au milieu du gué ",
            "courir plusieurs lièvres à la fois ",
            "crier au loup ",
            "crier comme un putois ",
            "devenir chèvre ",
            "donner de la confiture à des cochons ",
            "donner sa langue au chat ",
            "dormir comme un loir, dormir comme une marmotte ",
            "dormir en chien de fusil ",
            "enfermer le loup dans la bergerie ",
            "être à cheval sur les principes ",
            "être connu comme le loup blanc ",
            "être copains comme cochons ",
            "être doux comme un agneau ",
            "être myope comme une taupe ",
            "être pédé comme un phoque ",
            "être rusé comme un renard ",
            "être saoul comme un cochon ",
            "être un chaud lapin ",
            "être un ours mal léché ",
            "être un vieux loup de mer ",
            "faire la bête à deux dos ",
            "fait comme un rat ",
            "garder un chien de sa chienne ",
            "fièvre de cheval ",
            "hurler avec les loups ",
            "jeune loup aux dents longues ",
            "jouer au chat et à la souris ",
            "les chiens ne font pas des chats ",
            "manger comme un porc ",
            "marcher à pas de loup ",
            "ménager la chèvre et le chou ",
            "mettre la charrue avant les bœufs ",
            "miser sur le mauvais cheval ",
            "monter sur ses grands chevaux ",
            "ne pas avoir gardé les cochons ensemble ",
            "ne pas valoir un pet de lapin ",
            "parler français comme une vache espagnole ",
            "payer en monnaie de singe ",
            "peigner la girafe ",
            "pleuvoir comme vache qui pisse ",
            "poser un lapin ",
            "prendre le taureau par les cornes ",
            "remède de cheval ",
            "rentrer dans un trou de souris ",
            "revenir à ses moutons ",
            "s’ennuyer comme un rat mort ",
            "se jeter dans la gueule du loup ",
            "se regarder en chiens de faïence ",
            "se tailler la part du lion ",
            "sentir le fauve ",
            "sentir le fénec ",
            "sentir le phoque ",
            "traiter comme un chien ",
            "vendre la peau de l’ours avant de l’avoir tué ",
            "voir des éléphants roses ",
            "aller se faire cuire un œuf ",
            "avoir la chair de poule ",
            "avoir des ailes ",
            "avoir des mollets de coq ",
            "avoir un appétit d’oiseau ",
            "avoir une cervelle de moineau ou avoir une tête de linotte ",
            "à vol d’oiseau ",
            "bayer aux corneilles ou bailler aux corneilles ",
            "bavard comme une pie ",
            "ce n’est pas un aigle ",
            "le chant du cygne ",
            "clouer le bec ",
            "être chouette ",
            "être un oiseau pour le chat ",
            "être fier comme un paon ",
            "être gai comme un pinson ",
            "être le dindon de la farce ",
            "être léger comme une plume ",
            "être plein comme un œuf ",
            "être pris pour un pigeon ",
            "être un oiseau de mauvais augure ",
            "être un drôle d’oiseau ",
            "faute de grives, on mange des merles ",
            "faire le pied de grue ",
            "il fait un froid de canard ",
            "il tondrait un œuf ",
            "ne pas mettre tous les œufs dans le même panier ",
            "ne pas casser trois pattes à un canard ",
            "prendre sous son aile ",
            "petit à petit, l’oiseau fait son nid ",
            "pousser des cris d’orfraie ",
            "pratiquer la politique de l’autruche ",
            "quand les poules auront des dents ",
            "sauter du coq à l’âne ",
            "s’envoyer des noms d’oiseaux ",
            "se défendre bec et ongle ",
            "tuer la poule aux œufs d’or ",
            "vivre comme un coq en pâte ",
            "voler dans les plumes de quelqu’un ",
            "voler de ses propres ailes ",
            "y laisser des plumes ",
            "avaler des couleuvres ",
            "c’est le serpent qui se mord la queue ",
            "langue de vipère ",
            "verser des larmes de crocodiles ",
            "appuyer sur le champignon ",
            "avoir la pêche ",
            "avoir du blé ",
            "bête comme chou ",
            "chavirer dans le vétiver ",
            "conter fleurette ",
            "couper la poire en deux ",
            "courir sur le haricot ",
            "découvrir le pot aux roses ",
            "en avoir gros sur la patate ",
            "en pleine poire ",
            "en prendre de la graine ",
            "envoyer sur les roses ",
            "être dur de la feuille ",
            "être haut comme trois pommes ",
            "être une bonne poire ",
            "être, mettre sur la paille ",
            "faire chou blanc ",
            "faire le poireau ",
            "fauché comme les blés ",
            "être une grosse légume ",
            "les carottes sont cuites ",
            "manger les pissenlits par la racine ",
            "ménager la chèvre et le chou ",
            "ne pas sentir la rose ",
            "passer à tabac ",
            "poirier ",
            "pousser comme des champignons ",
            "prendre racine ",
            "raconter des salades ",
            "ramener sa fraise ",
            "s’accrocher aux branches ",
            "scier la branche sur laquelle on est assis ",
            "se dégorger le poireau ",
            "se porter comme un charme ",
            "se reposer sur ses lauriers ",
            "s’envoyer des fleurs ",
            "séparer le bon grain de l’ivraie ",
            "sucrer les fraises ",
            "tirer les marrons du feu ",
            "toucher du bois ",
            "tomber dans les pommes ",
            "vendre sa salade ",
            "bon enfant ",
            "déshabiller Pierre pour habiller Paul ",
            "enfant de chœur ",
            "enfant de roi ",
            "enfant de troupe ",
            "faire l’enfant ",
            "filer à l’anglaise ",
            "mentir comme un arracheur de dents ",
            "pleurer comme une Madeleine ",
            "vendre père et mère ",
            "vieux de la vieille ",
            "aller à la soupe ",
            "aller se faire cuire un œuf ",
            "avoir de la bouteille ",
            "avoir du pain sur la planche ",
            "ça baigne ",
            "chercher le poil dans l’œuf ",
            "coup de fourchette ",
            "couper la poire en deux ",
            "cracher dans la soupe ",
            "dur à cuire ",
            "en avoir gros sur la patate ",
            "en avoir ras le bol ",
            "en faire tout un fromage ",
            "en faire tout un plat ",
            "mettre les pieds dans le plat ",
            "entrer dans le moule ",
            "être comme deux ronds de flan (ou comme deux ronds de frites) ",
            "être à ramasser à la petite cuiller ",
            "être une tête de lard ",
            "faire chou blanc (faussement ; voir l’étymologie) ",
            "faire un four ",
            "gagner son pain, avoir un gagne-pain ",
            "manger les pissenlits par la racine ",
            "manger son blé en herbe ",
            "marcher sur des œufs ",
            "mettre de l’eau dans son vin ",
            "mettre du beurre dans les épinards ",
            "mettre la main à la pâte ",
            "mettre les petits plats dans les grands ",
            "mettre tous les œufs dans le même panier ",
            "ne pas être dans son assiette ",
            "ne pas manger de ce pain là ",
            "ne pas perdre une miette ",
            "ne pas y aller avec le dos de la cuillère ",
            "partir en biberine ; partir en sucette ; partir en cacahuète ",
            "pousser comme des champignons ",
            "recette du succès ",
            "rendre son tablier ",
            "rester en carafe ",
            "se fendre la poire ",
            "tomber dans les pommes ",
            "veiller au grain ",
            "vouloir le beurre et l’argent du beurre, vouloir le beurre, l’argent du beurre, et le sourire de la crémière ou vouloir le beurre, l’argent du beurre et le cul de la crémière ",
            "entre la poire et le fromage ",
            "avaler de travers ",
            "avaler la pilule ",
            "avoir la dalle ",
            "avoir la gueule de bois ",
            "avoir les dents du fond qui baignent ",
            "avoir l’estomac dans les talons ",
            "avoir mal aux cheveux ",
            "avoir une faim de loup ",
            "avoir un estomac d’autruche ",
            "boire du petit-lait ",
            "boire la tasse ",
            "casser la croûte ",
            "couler un bronze ",
            "crever la dalle ",
            "de mauvais goût ",
            "démouler un cake ",
            "être soupe au lait ",
            "être sur le gril ",
            "faire pleurer Mirza ",
            "mâcher le travail ",
            "mâcher ses mots, ne pas mâcher ses mots ",
            "machon-gorgeon ",
            "mâchon gorgeon ",
            "manger avec un lance-pierre ",
            "rester sur l’estomac ",
            "rester sur sa faim ",
            "se boire comme du petit-lait ",
            "se lécher les babines ",
            "se mettre à table ",
            "accorder son temps- en accord avec son temps ",
            "attendre son heure ",
            "avoir de beaux jours devant soi ",
            "avoir du temps à perdre ",
            "avoir fait son temps ",
            "avoir le temps ",
            "c’est pas demain la veille que ",
            "consacrer son temps ",
            "donner son temps ",
            "durer trois plombes ",
            "être de son temps ",
            "être temps ",
            "faire beau ",
            "faire des vacances ",
            "faire la grasse matinée ",
            "faire quelque chose de son temps ",
            "faire son temps ",
            "faire un bail ",
            "finir son temps ",
            "gaspiller son temps ",
            "minute papillon ",
            "ne pas perdre une seconde ",
            "passer son temps ",
            "perdre son temps ",
            "prendre du bon temps ",
            "prendre son mal en patience ",
            "prendre son temps ",
            "tuer le temps ",
            "ajouter une pierre à l’édifice ",
            "avoir l’étoffe de ",
            "avoir un caractère bien trempé ",
            "avoir le feu sacré ",
            "brûler la chandelle par les deux bouts ",
            "croire dur comme fer ",
            "être givré ",
            "être tout feu tout flamme ",
            "faire d’une pierre deux coups ",
            "faire feu de tout bois ",
            "faire flèche de tout bois ",
            "faire la planche ",
            "filer du mauvais coton ",
            "fumer comme un pompier ",
            "geler à pierre fendre ",
            "grimper aux rideaux / grimper au rideau ",
            "jouer avec le feu ",
            "mettre de l’huile sur le feu ",
            "jeter de l’huile sur le feu ",
            "mettre de l’huile dans les rouages ",
            "mettre le feu aux poudres ",
            "mordre la poussière ",
            "nager comme une pierre ",
            "nager comme une enclume ",
            "nager comme un fer à repasser ",
            "ne pas manquer d’air ",
            "n’y voir que du feu ",
            "parler chiffons ",
            "partir en fumée ",
            "passer l’éponge ",
            "pousser le bouchon ",
            "se foutre en l’air ",
            "tourner en eau de boudin ",
            "vivre d’amour et d’eau fraîche ",
            "attendre le dégel ",
            "avoir de beaux jours devant soi ",
            "avoir un coup de foudre ",
            "atteindre des sommets ",
            "en faire toute une montagne ",
            "faire la pluie et le beau temps ",
            "il y a de l’orage dans l’air ",
            "jeter un froid ",
            "ne faire ni chaud ni froid ",
            "passer entre les gouttes ",
            "pleuvoir à boire debout ",
            "pleuvoir comme vache qui pisse ",
            "pleuvoir des cordes ",
            "pleuvoir des hallebardes ",
            "à marquer d’une pierre blanche ",
            "agiter le chiffon rouge ",
            "annoncer la couleur ",
            "avoir carte blanche ",
            "avoir la main verte ",
            "avoir une peur bleue ",
            "blanc bonnet et bonnet blanc ",
            "broyer du noir ",
            "chou vert et vert chou ",
            "donner le feu vert ",
            "en voir de toutes les couleurs ",
            "en voir des vertes et des pas mûres ",
            "en dire des vertes et des pas mûres ",
            "être cousu de fil blanc ",
            "être fleur bleue ",
            "être la bête noire de quelqu'un ",
            "faire chou blanc ",
            "faire couleur locale ",
            "faire grise mine ",
            "marquer d'une pierre blanche ",
            "montrer patte blanche ",
            "noircir le tableau ",
            "rire jaune ",
            "saigner à blanc ",
            "se faire avoir comme un bleu ",
            "se faire des cheveux blancs ",
            "se mettre au vert ",
            "tirer à boulets rouges ",
            "voir la vie en rose ",
            "voir rouge ",
            "rouge comme une tomate ",
            "rouge comme une écrevisse ",
            "rouge sang ",
            "battre en retraite ",
            "battre la chamade ",
            "changer son fusil d’épaule ",
            "déposer les armes ",
            "déterrer la hache de guerre ",
            "faire fissa ",
            "l’échapper belle ",
            "ouvrir les hostilités ",
            "passer au fil de l’épée ",
            "passer l’arme à gauche ",
            "prendre du galon ",
            "s’en soucier comme de l’an quarante ",
            "signer son arrêt de mo ",
            "beau comme un camion ",
            "charger la barque ",
            "démarrer au quart de tour ",
            "démarrer sur les chapeaux de roues ",
            "être à la masse ",
            "être la cinquième roue du carrosse ",
            "être la roue de secours ",
            "faire la roue ",
            "faire machine arrière ",
            "être pédé comme un foc ",
            "marcher à voile et à vapeur ",
            "mettre les voiles ",
            "mener en bateau ",
            "mener grand train ",
            "perdre les pédales ",
            "péter les plombs ",
            "péter un câble ",
            "ronger son frein ",
            "rouler comme un moine ",
            "rouler des mécaniques ",
            "s’acheter une conduite ",
            "virer de bord ",
            "à l’unisson ",
            "accorder ses violons ",
            "chanter comme une casserole ",
            "connaitre la chanson ",
            "connaître la musique ",
            "envoyer valser ",
            "être réglé comme du papier à musique ",
            "faire péter les watts ",
            "faire un couac ",
            "fausse note ",
            "jouer du pipeau ",
            "lâcher le morceau ",
            "lâcher une caisse ",
            "mener à la baguette ",
            "mettre un bémol ",
            "la mettre en sourdine ",
            "se mettre au diapason ",
            "son de cloche ",
            "tenir le rythme ",
            "y aller crescendo ",
            "avoir la main heureuse ",
            "avoir de la chatte ",
            "avoir du bol ",
            "avoir du pot ",
            "avoir le cul bordé de nouilles ",
            "avoir une veine de cocu ; avoir une chance de cocu ",
            "décrocher la timballe ",
            "être plein aux as ",
            "être verni ",
            "l’avoir échappé belle ",
            "toucher du bois[3] ",
            "avoir la poisse ",
            "avoir la scoumoune ",
            "être noir ",
            "abattre ses cartes ",
            "annoncer la couleur ",
            "arriver dans un fauteuil ",
            "avoir le nez dans le guidon ",
            "avoir plusieurs cordes à son arc ",
            "botter en touche ",
            "coiffer sur le poteau ",
            "damer le pion ",
            "entrer dans le jeu de quelqu’un ",
            "être faux comme un jeton, être un faux jeton ",
            "être dans les starting blocks ",
            "faire cavalier seul ",
            "il va y avoir du sport ",
            "jeu de main, jeu de vilain ",
            "jouer cartes sur table ",
            "jouer son va-tout ",
            "lever l’ancre ",
            "mettre les voiles ",
            "nager dans le bonheur ",
            "on va tout péter ",
            "passer sur le billard ",
            "renvoyer dans ses vingt-deux ",
            "saisir la balle au bond ",
            "sortir le grand jeu ",
            "se jeter dans la mêlée ",
            "tirer son épingle du jeu ",
            "de l’argent sale ",
            "avoir maille à partir ",
            "avoir un oursin dans sa poche ",
            "blanchir de l’argent ",
            "coûter la peau des fesses ",
            "en mettre à gauche ",
            "être un panier percé ",
            "jeter son argent par les fenêtres ",
            "ne pas avoir un sou vaillant ",
            "mettre du beurre dans les épinards ",
            "payer avec un lance-pierre ",
            "payer en monnaie de singe ",
            "payer rubis sur l’ongle ",
            "prendre pour argent comptant ",
            "rouler sur l’or ",
            "vouloir le beurre et l’argent du beurre ",
            "à la six-quatre-deux ",
            "aligner les zéros ",
            "avoir le moral à zéro ",
            "chercher midi à quatorze heures ",
            "dire ses quatre vérités à quelqu’un ",
            "durer trois plombes ",
            "en deux temps trois mouvements ",
            "être au septième ciel ",
            "être au trente-sixième dessous ",
            "être haut comme trois pommes ",
            "être la cinquième roue du carrosse ",
            "jamais deux sans trois ",
            "le 36 du mois ",
            "monter quatre à quatre ",
            "ne faire ni une ni deux ",
            "ne pas y aller par quatre chemins ",
            "remettre les compteurs à zéro ",
            "remettre les pendules à l’heure ",
            "repartir comme en quarante ",
            "se mettre en quatre ",
            "se mettre sur son trente-et-un ",
            "se prendre pour la huitième merveille du monde ",
            "se retrouver les quatre fers en l’air ",
            "treize à la douzaine ",
            "trois fois rien ",
            "voir midi à sa porte ",
            "voir trente-six chandelles ",
            "faire trente-six chose à la fois ",
            "en perdre son latin ",
            "être de l’hébreu ",
            "être du chinois ",
            "filer à l’anglaise ",
            "parler comme un basque espagnol ",
            "parler français comme une vache espagnole ",
            "promesse de gascon ",
            "tomber de Charybde en Scylla ",
            "boire comme un polonais ",
            "aller au diable ou aller au Diable ",
            "attendre le déluge ",
            "avoir le diable au corps ",
            "avoir un cœur d’ange ",
            "donner le bon Dieu sans confession ",
            "faire sa sainte ni touche ",
            "la croix et la bannière ",
            "laid comme les sept péchés capitaux ",
            "le diable est aux vaches ",
            "ne connaître ni d’Ève ni d’Adam ",
            "ne pas l’emporter au paradis ",
            "pleurer comme une Madeleine ",
            "remonter au déluge ",
            "rendre l’âme ",
            "se répandre comme la vérole sur le bas-clergé ",
            "sonner le glas ",
            "tendre l'autre joue ",
            "tirer le diable par la queue ",
            "vendre son âme au diable ",
            "apporter de l’eau à son moulin ",
            "être au four et au moulin ",
            "gagner son pain ",
            "mâcher le travail ",
            "parler boutique ",
            "récolter ce que l’on a semé ",
            "se battre comme des chiffonniers ",
            "travailler au noir ",
            "travailler d'arrache pied ",
            "trier sur le volet ",
            "avoir de la moule ",
            "avoir du cul ",
            "avoir le cul bordé de nouilles ",
            "avoir le cul entre deux chaises ",
            "avoir le feu aux fesses ",
            "avoir le feu au cul ",
            "avoir un balai dans le cul ",
            "casser les couilles ",
            "couille de loup ",
            "coûter la peau du cul ",
            "coûter la peau des fesses ",
            "nez de bœufs ",
            "partir en couille ",
            "péter plus haut que son cul ",
            "se faire des couilles en or ",
            "se faire voir chez les Grecs ",
            "se magner le cul ",
            "s’en battre les couilles ",
            "s’en battre l’œil ",
            "s’en torcher le cul ",
            "se péter la rondelle ",
            "se sortir les doigts du cul ",
            "se vider les couilles ",
            "trouer le cul ",
            "y avoir une couille dans le pâté ",
            "une couille dans le potage ",
            "chier une pendule ",
            "en avoir jusque là ",
            "envoyer chier ",
            "être dans la merde, être dans la merde jusqu’au cou ",
            "faire chier ",
            "lâcher la grappe, lâcher les baskets ",
            "n’en avoir rien à braire ",
            "n'en avoir rien à foutre ",
            "rien à carrer ",
            "n’en avoir rien à secouer ",
            "nœud-nœud ",
            "partir en cacahuète ",
            "partir en sucette ",
            "partir en live ",
            "partir en vrille ",
            "partir en couille ",
            "péter les plombs ",
            "péter un câble ",
            "péter plus haut que son cul ",
            "pisser dans un violon ",
            "se faire des nœuds ",
            "acquérir des lettres de noblesse ",
            "avoir la boule au ventre ",
            "avoir les boules ",
            "avoir les fils qui se touchent ",
            "avoir plus d’un tour dans son sac ",
            "avoir plusieurs casquettes ",
            "avoir un polichinelle dans le tiroir ",
            "avoir une brique dans le ventre ",
            "battre à plate couture ",
            "casser sa pipe ",
            "chercher une aiguille dans une meule de foin ",
            "coller aux basques ",
            "créer de toute pièce ",
            "dépasser les bornes ",
            "devoir une fière chandelle ",
            "donner du fil à retordre ",
            "éclairer sa lanterne ",
            "enfiler les perles ",
            "être sur la paille ",
            "joindre les deux bouts ",
            "le torchon brûle ",
            "maquillée comme un camion volé ",
            "mélanger les torchons et les serviettes ",
            "mener à la baguette ",
            "mener une vie de bâton de chaise ",
            "mettre le grappin sur quelqu’un ",
            "mordre à l’hameçon ",
            "mourir dans son lit ",
            "ne pas avoir inventé le fil à couper le beurre ",
            "ne pas avoir inventé la poudre ",
            "ne pas être à prendre avec des pincettes ",
            "ne pas lâcher d’une semelle ",
            "ne pas valoir un clou ",
            "ne pas valoir la corde pour le pendre ",
            "passer à travers les mailles d’un filet ",
            "passer un savon ",
            "perdre le fil ",
            "remuer le couteau dans la plaie ",
            "rouler une pelle ",
            "se mélanger les pinceaux ",
            "se prendre un rateau ",
            "tendre la perche ",
            "tendu comme un string ",
            "tenir la chandelle ",
            "tomber dans le panneau ",
            "toucher la corde sensible ",
            "tourner autour du pot ",
            "bâtir des châteaux en Espagne ",
            "battre le pavé ",
            "crever le plafond ",
            "crier sur les toits, crier sur tous les toits ",
            "déménager à la cloche de bois ",
            "déménager sans tambour ni trompette ",
            "écouter aux portes ",
            "en boucher un coin ",
            "entrer par la grande porte ",
            "sortir par la grande porte ",
            "épater la galerie ",
            "faire le pont ",
            "frapper à la bonne porte ",
            "jeter aux oubliettes ",
            "mettre à la porte ",
            "mettre la clé sous la porte ",
            "monter au créneau ",
            "ne pas être sorti de l’auberge ",
            "ne pas se bousculer au portillon ",
            "onduler de la toiture ",
            "pendre la crémaillère ",
            "ravaler la façade ",
            "renvoyer l’ascenseur ",
            "sauver les meubles ",
            "sortir par la porte ",
            "entrer par la fenêtre ",
            "tâter le terrain ",
            "voir le bout du tunnel ",
            "aller voir ailleurs ",
            "arrondir les angles ",
            "avaler un obstacle ",
            "avoir déjà donné ",
            "avoir la cote ",
            "avoir la science infuse ",
            "avoir le coup de foudre ",
            "avoir son content ",
            "baisser d’un ton ",
            "battre en brèche ",
            "battre la campagne ",
            "battre son plein ",
            "briller par son absence ",
            "briser la glace ",
            "courir le guilledou, la galipote ",
            "cracher au bassinet ",
            "dire ses quatre vérités à quelqu’un ",
            "en faire des tonnes ",
            "entrer dans le vif du sujet ",
            "entrer en lice ",
            "être à l’index ",
            "être au trente-sixième dessous ",
            "être de parole ",
            "être donnant donnant ",
            "être parti pour durer ",
            "être une lumière ",
            "faire amende honorable ",
            "faire avancer le schmilblic ",
            "faire des comptes d’apothicaire ",
            "faire des siennes ",
            "faire la part des choses ",
            "faire le point ",
            "faire tapisserie ",
            "faire une croix sur quelque chose ",
            "joindre les deux bouts ",
            "lâcher la proie pour l’ombre ",
            "laisser dans le margouillis ",
            "marquer le pas ",
            "mettre les points sur les i ",
            "mettre les points sur les i et les barres sur les t ",
            "ne pas en revenir ",
            "ne pas briller de mille feux ",
            "parler à mots couverts ",
            "parler pour ne rien dire ",
            "partir à vau l’eau ",
            "passer à l’as ",
            "passer son chemin ",
            "percer à jour ",
            "porter la culotte ",
            "porter le chapeau ",
            "prendre à la légère ",
            "prendre dans sa toile ",
            "prendre des mesures ",
            "prendre la poudre d’escampette ",
            "prendre la tangente ",
            "prendre le pli ",
            "promettre monts et merveilles ",
            "raconter des craques ",
            "réfléchir à deux fois ",
            "rendre à César ce qui est à César ",
            "rester sur sa faim ",
            "retourner sa veste ",
            "rompre le charme ",
            "se donner à fond ",
            "se faire tout petit ",
            "se prendre les pieds dans le tapis ",
            "sortir des sentiers battus ",
            "sortir d’un chapeau ",
            "suivre son petit bonhomme de chemin ",
            "continuer son petit bonhomme de chemin ",
            "tenir le bon bout ",
            "tenir le haut du pavé ",
            "tenir parole ",
            "tirer la couverture à soi ",
            "tirer sa révérence ",
            "tirer un trait ",
            "tomber à l’eau ",
            "tomber à pic ",
            "tomber de haut ",
            "tomber des nues ",
            "tourner comme une girouette ",
            "valoir le détour ",
            "bête noire ",
            "blanc-bec ",
            "bouc émissaire ",
            "canard boiteux ",
            "être le canari dans la mine ",
            "capote anglaise ",
            "chair de poule ",
            "cheval de bataille ",
            "clef anglaise ",
            "coup de main ",
            "coup de pied de l’âne ",
            "envoyé spécial ",
            "faire la bête à deux dos ",
            "feuille de chou ",
            "fine mouche ",
            "franc comme un âne qui recule ",
            "froid de canard ",
            "homme de la situation ",
            "homme de paille ",
            "la cerise sur le gâteau ",
            "l’arbre qui cache la forêt ",
            "loup de mer ",
            "mouton de Panurge ",
            "nid de poule ",
            "œil de lynx ",
            "oie blanche ",
            "oiseau de malheur ",
            "part du lion ",
            "pauvre diable ",
            "pied à terre ",
            "pied-de-biche ",
            "pied de nez ",
            "pipi de chat ",
            "plancher des vaches ",
            "politique de Gribouille ",
            "politique de l’autruche ",
            "poule de luxe ",
            "poule mouillée ",
            "renard libre dans le poulailler libre ",
            "secret de Polichinelle ",
            "temps de chien ",
            "tête de linotte ",
            "tête de Turc ",
            "travail de fourmi ",
            "victoire à la Pyrrhus ",
            "vieux renard ",
            "yeux de merlan frit ",
            "le bras droit ",
            "cœur d’artichaut ",
            "cœur de pierre ",
            "coup d’œil ",
            "de la poudre aux yeux ",
            "la grosse tête ",
            "main courante ",
            "main pleine de doigts ",
            "œil au beurre noir ",
            "poil de carotte ",
            "prise de tête ",
            "sang froid ",
            "un tête à queue ",
            "une tête de mule ",
            "c’est la mer à boire ",
            "coup d’éclat ",
            "coup de Jarnac ",
            "coup d’épée dans l’eau ",
            "coup de Trafalgar ",
            "coup du père François ",
            "course contre la montre ",
            "faire le poirier ",
            "politique du chien crevé au fil de l’eau ",
            "un éclair de génie ",
            "cinquième roue du carrosse ",
            "coup de foudre ",
            "drache nationale ",
            "fil rouge ",
            "fleur bleue ",
            "largeur de vues ",
            "la semaine des quatre jeudis ",
            "le 36 du mois ",
            "mise à pied ",
            "nuit blanche ",
            "petit joueur ",
            "peur bleue ",
            "pièce rapportée ",
            "preuve par neuf ",
            "sac de nœuds ",
            "Saint-Clinclin ou à la Saint-Glinglin ",
            "septième ciel ",
            "solution de continuité ",
            "trois fois rien ",
            "usine à gaz ",
            "beau comme un dieu ",
            "bête comme ses pieds ",
            "comme chien et chat ",
            "comme des harengs ",
            "comme des sardines ",
            "comme un cheveu sur la soupe ",
            "comme un coq en pâte ",
            "comme un éléphant dans un magasin de porcelaine ",
            "comme un poisson dans l’eau ",
            "connu comme le loup blanc ",
            "content comme une cane ",
            "fier comme Artaban ",
            "fait comme un haricot, faits comme des haricots ",
            "fier comme un coq ",
            "fier comme un paon ",
            "fier comme un pape ",
            "fier comme un pou ",
            "fait comme un rat ",
            "fort comme un Turc ",
            "frais comme un gardon ",
            "gai comme un pinson, gaie comme une pinsonne ",
            "haut comme trois pommes ",
            "heureux comme un poisson dans l’eau ",
            "malin comme un singe ",
            "mi-figue, mi-raisin ",
            "muet comme une carpe ",
            "muet comme une tombe ",
            "nu comme un ver ",
            "pauvre comme Job ",
            "plat comme une limande ",
            "riche comme Crésus ",
            "ridée comme une veille pomme ",
            "sérieux comme un pape ",
            "têtu comme un âne ",
            "têtu comme une bourrique ",
            "têtu comme un mule ",
            "un tissu pied-de-poule ",
            "voleuse comme une pie ",
            "à poil ",
            "armé jusqu’aux dents ",
            "au nez et à la barbe ",
            "comme cul et chemise ",
            "comme le nez au milieu de la figure ",
            "les quatre fers en l’air ",
            "partie de jambes en l’air ",
            "tiré par les cheveux ",
            "blanc comme neige ",
            "blanc comme un cachet d’aspirine ",
            "blanc comme un linge ",
            "blanc comme un navet ",
            "blanc comme une merde de laitier ",
            "cousu de fil blanc ",
            "dans le rouge ",
            "écrit noir sur blanc ",
            "frais comme une rose ",
            "noir de monde ",
            "rouge comme un coq ",
            "rouge comme un coquelicot ",
            "rouge comme un homard ",
            "rouge comme une cerise ",
            "rouge comme une écrevisse ",
            "rouge comme une pivoine ",
            "rouge comme une tomate ",
            "rouge de colère ",
            "vert de jalousie ",
            "vert de rage ",
            "au pied du mur ",
            "en roue libre ",
            "être dans de beaux draps ",
            "être dans le pétrin ",
            "être le dos au mur ",
            "être sous les projecteurs ",
            "sur le pied de guerre ",
            "à bout ",
            "dans la lune ",
            "droit comme un i ",
            "en reste ",
            "fou à lier ",
            "fou comme un balai ",
            "franco-français ",
            "gai comme le canal ",
            "gravé dans le marbre ",
            "long à la détente ",
            "maigre comme un clou ",
            "plein aux as ",
            "poivre et sel ",
            "rond comme une queue de pelle ",
            "sans foi ni loi ",
            "terre à terre ",
            "tout feu tout flammes ",
            "tout sucre tout miel ",
            "à la fleur de l’âge ",
            "à la noix ",
            "au ras des pâquerettes ",
            "aux anges ",
            "aux frais de la princesse ",
            "baiser comme un lapin ",
            "dans l’œuf ",
            "dès potron-minet ",
            "entre chien et loup ",
            "pour des prunes ",
            "à bras ouverts ",
            "à corps perdu ",
            "à l’œil nu ",
            "à pied d’œuvre ",
            "à tue tête ",
            "à un doigt ",
            "à vue de nez ",
            "au petit pied ",
            "au pied de la lettre ",
            "au pied du mur ",
            "comme cul et chemise ",
            "de la tête aux pieds ",
            "de tout son long ",
            "en tête à queue ",
            "en travers de la gorge ",
            "la bouche en cœur ",
            "la queue entre les jambes ",
            "les doigts dans le nez ",
            "les mains dans les poches ",
            "main dans la main ",
            "mener par le bout du nez ",
            "pied levé ",
            "plein les yeux ",
            "sur le bout de la langue ",
            "sur le pouce ",
            "à bride abattue ",
            "à fond la caisse ",
            "à fond les ballons ",
            "à hue et à dia ",
            "à tombeau ouvert ",
            "à tort et à travers ",
            "au tournant ",
            "pied au plancher ",
            "à fleuret moucheté ",
            "à hue et à dia ",
            "à la belle étoile ",
            "à la louche ",
            "à la mords-moi-le-nœud ",
            "à la queue leu-leu ",
            "à la six-quatre-deux ",
            "à la va comme je te pousse ",
            "à l’emporte-pièce ",
            "à l’instar de ",
            "à perdre haleine ",
            "à qui mieux mieux ",
            "à tire-larigot ",
            "au petit bonheur la chance ",
            "avoir la frite ",
            "avoir le coup de foudre ",
            "casser les pieds ",
            "clopin-clopant ",
            "dans le tas ",
            "d’arrache-pied ",
            "de bonne guerre ",
            "de but en blanc ",
            "donner sa langue au chat ",
            "en douce ",
            "en faire tout un fromage, en faire un fromage ",
            "en un clin d’œil ",
            "en un tour de main ",
            "en un tournemain ",
            "entre quatre yeux ",
            "être lessivé ",
            "haut la main ",
            "jusqu’à plus soif ",
            "les doigts dans le nez ",
            "mine de rien ",
            "pour tout un régiment ",
            "sans avoir l’air d’y toucher ",
            "se faire rouler dans la farine ",
            "se tenir à carreau ",
            "sur un autre ton ",
            "travailler au noir ",
            "à la Saint-Glinglin ",
            "aux calendes grecques ",
            "ce n’est pas demain la veille que ",
            "il était une fois ",
            "jusqu’à nouvel ordre ",
            "semaine aux quatre jeudis ",
            "un brouillard à couper au couteau ",
            "à mon sens ",
            "à tort ou à raison ",
            "au diable Vauvert ",
            "au fur et à mesure ",
            "au saut du lit ",
            "au tapis ",
            "comme deux gouttes d’eau ",
            "dans le collimateur ",
            "dans le mille ",
            "dans les grandes largeurs ",
            "de proche en proche ",
            "de derrière les fagots ",
            "Dieu merci ",
            "en double file ",
            "être à tu et à toi ",
            "laisser la lumière sous le boisseau ",
            "par la force des choses ",
            "petit à petit ",
            "sens dessus dessous ",
            "sous peine de ",
            "sur un petit nuage ",
            "bon sang ! ",
            "ça craint ! ",
            "c’est comme si vous chantiez ",
            "c’est la croix et la bannière ",
            "c’est râpé ! ",
            "chapeau bas ! ",
            "des clous ! ",
            "des nèfles ! ",
            "la vérité si je mens ! ",
            "minute papillon ",
            "mon dieu ! ",
            "quelle mouche l’a piqué ? ",
            "rien n’est joué ",
            "à bon chat, bon rat ",
            "à cœur sans but, cœur fidèle ",
            "adieu Berthe ",
            "advienne que pourra ",
            "après l’effort, le réconfort ",
            "à Rome, fais comme les Romains ",
            "au diable l’avarice ",
            "bonnet blanc, blanc bonnet ",
            "bon débarras ! ",
            "ça coûte la peau des fesses ",
            "ça crève les yeux ",
            "ça ne casse pas des barres ",
            "ça ne casse pas trois pattes à un canard ",
            "ça ne casse rien ",
            "ça ne se bouscule pas au portillon ",
            "ça me fait une belle jambe ",
            "ce n’est pas la peine ",
            "c’est à prendre ou à laisser ",
            "c’est beaucoup dire ",
            "c’est bien fait, c’est bien fait pour quelqu’un ",
            "c’est comme ça (et c’est pas autrement) ",
            "c’est de la balle ",
            "c’est la fin des haricots ",
            "c’est le serpent qui se mord la queue ",
            "c’est pas du jeu ",
            "c’est un jeu d’enfants ",
            "circulez y’a rien à voir ",
            "demain on rase gratis ",
            "deux poids, deux mesures ",
            "il faut acheter au son du canon et vendre au son du clairon ",
            "il faut de tout pour faire un monde ",
            "il ne faut pas pousser mémé dans les hortensias ",
            "il ne faut pas pousser mémé dans les orties ",
            "il n’y a pas un chat ",
            "il n’y a pas le feu au lac ",
            "tous les chemins mènent à Rome ",
            "la bave du crapaud n’atteint pas la blanche colombe ",
            "la goutte d’eau qui fait déborder le vase ",
            "la meilleure défense c’est l’attaque ",
            "la montagne a accouché d’une souris ",
            "les bras m’en tombent, les bras lui en tombent ",
            "les carottes sont cuites ",
            "les déficits d’aujourd’hui font les impôts de demain ",
            "les dés sont pipés ",
            "les mouches ont changé d’âne ",
            "l’étincelle qui met le feu aux poudres ",
            "mon œil ! ",
            "mon petit doigt m’a dit ",
            "on ne sait jamais (dans la vie) ",
            "pan, dans les narines ",
            "quelle prise de tête ! ",
            "son sang ne fit qu’un tour ",
            "tel qui rit vendredi dimanche pleurera ",
            "toute serrure a sa clé ",
            "tout nouveau, tout beau ",
            "un clou chasse l’autre ",
            "une main de fer dans un gant de velours ",
            "vlan dans les dents "};
    private static final int REQ_CODE_SPEECH_INPUT = 100;
    private TextView mVoiceInputTv;
    private ImageButton mSpeakBtn;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.talk);

        mVoiceInputTv = (TextView) findViewById(R.id.voiceInput);
        mSpeakBtn = (ImageButton) findViewById(R.id.btnSpeak);
        mSpeakBtn.setOnClickListener(new View.OnClickListener() {

            @Override
            public void onClick(View v) {
                startVoiceInput();
            }
        });
    }

    public void talk(View view) {

        Intent startNewActivity  = new Intent(this, wait.class);
        startActivity(startNewActivity);

        //startActivity(new Intent(this, wait.class));
    }

    private void startVoiceInput() {
        Intent intent = new Intent(RecognizerIntent.ACTION_RECOGNIZE_SPEECH);
        intent.putExtra(RecognizerIntent.EXTRA_LANGUAGE_MODEL, RecognizerIntent.LANGUAGE_MODEL_FREE_FORM);
        intent.putExtra(RecognizerIntent.EXTRA_LANGUAGE, Locale.getDefault());
        intent.putExtra(RecognizerIntent.EXTRA_PROMPT, "Hello, How can I help you?");
        try {
            startActivityForResult(intent, REQ_CODE_SPEECH_INPUT);
        } catch (ActivityNotFoundException a) {

        }
    }

    @Override
    protected void onActivityResult(int requestCode, int resultCode, Intent data) {
        super.onActivityResult(requestCode, resultCode, data);

        switch (requestCode) {
            case REQ_CODE_SPEECH_INPUT: {
                if (resultCode == RESULT_OK && null != data) {
                    ArrayList<String> the_way = new ArrayList<String>();
                    the_way.add("do you know the way");
                    ArrayList<String> result = data.getStringArrayListExtra(RecognizerIntent.EXTRA_RESULTS);
                    if(the_way.get(0).equals(result.get(0))){
                        ArrayList<String> new_way = new ArrayList<String>();
                        new_way.add("I know the way,brotherrrrrrrrr");
                        mVoiceInputTv.setText(new_way.get(0));
                    } else {
                        mVoiceInputTv.setText(result.get(0));
                    }
                }
                break;
            }
        }
    }
    // Test if the string "str" is in the string "txt"
    boolean is_in(String str, String txt){
        int i = 0;
        int str_i = 0;
        char str_char[] = str.toCharArray();
        char txt_char[] = txt.toCharArray();
        while (txt_char[i] != 0){
            if (txt_char[i] == str_char[str_i]){
                str_i++;
                if (str_char[str_i] == 0)
                    return true;
            }
            else
                str_i = 0;
            i++;
        }
        return false;
    }

    //Transforme tous les caracteres speciaux en caracteres non-speciaux
    void non_utf8(String txt){
        int i = 0;
        char txt_char[] = txt.toCharArray();
        while (txt_char[i] != 0){
            if ((txt_char[i] == 'é') || (txt_char[i] == 'è') || (txt_char[i] == 'ê') || (txt_char[i] == 'e'))
                txt_char[i] = 'e';
            if ((txt_char[i] == 'a') || (txt_char[i] == 'â') || (txt_char[i] == 'ä'))
                txt_char[i] = 'a';
            if (txt_char[i] == 'ô' || txt_char[i] == 'ö')
                txt_char[i] = 'o';
            if ((txt_char[i] == 'ù') || (txt_char[i] == 'û'))
                txt_char[i] = 'u';
            i++;
        }
    }


    //Coupe une chaine de caractere en un tableau de mots
    String[] split(String txt){
        int i = 0;
        String array[] = {""};
        String tmp = "";
        char txt_char[] = txt.toCharArray();
        while (txt_char[i] != 0){
            if ((txt_char[i] != ' ') && (txt_char[i] != ',') && (txt_char[i] != ';') && (txt_char[i] != '.') && (txt_char[i] != '(') && (txt_char[i] != ')') && (txt_char[i] != '?') && (txt_char[i] != '!') && (txt_char[i] != ':')){
                tmp.add(txt_char[i]);
            }
            else{
                array.add(tmp);
                tmp = "";
            }
            i++;
        }
        return array;
    }

    public String[] Init(String expr[]) {
        Random rand = new Random();
        int randNumber = rand.nextInt(1401);
        String expr_to_find = expr[randNumber];
        non_utf8(expr_to_find);
        String list_to_find[] = split(expr_to_find);
        return list_to_find;
    }

    public int words_found(String expr_to_find[], String expr_given) {
        non_utf8(expr_given);
        String list_given[] = split(expr_given);
        int words_found = 0;
        for(int i = 0; i < list_given.length; i++) {
            for(int j = 0; j < expr_to_find.length; j++) {
                if (is_in(list_given[i], expr_to_find[j])) {
                    words_found++;
                }
            }
        }
        return words_found;
    }
}